name: mito
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.6
  - numpy=1.22.4
  - scipy=1.9.0
  - pandas==1.5.3
  - anndata=0.8.0
  - networkx=2.8.6
  - python-igraph=0.9.11
  - leidenalg=0.8
  - matplotlib=3.5.3
  - seaborn=0.11.2
  - scanpy=1.9.1
  - scikit-learn=1.1.2
  - yaml=0.2.5
  - pysam
  - conda-build
  - pip
  - pip:
      - cvxpy==1.3
      - Biopython==1.71
      - bokeh==0.12.15
      - ete3==3.1.1
      - ngs-tools==1.5.6
      - plotly==5.0.0
      - pyseq-align==1.0.2
      - itolapi
      - hits
      - PyYAML
      - parameterized
      - circlify
      - plotting_utils==0.1.2
      - mquad==0.1.8
      - sphinx==8.1.3
      - sphinx-rtd-theme
      - sphinx-autodoc-typehints
      - sphinxcontrib-napoleon

